import 'package:flutter/material.dart';

class LocalizationService {
  static final Map<String, Map<String, String>> _localizedValues = {
    'es': {
      'app_title': 'Mamitas AI',
      'patients': 'Pacientes',
      'analysis': 'Análisis',
      'results': 'Resultados',
      'database': 'Base de datos',
      'settings': 'Configuración',
      'help': 'Ayuda',
      'home': 'Inicio',
      'language': 'Idioma',
      'data': 'Datos',
      'clear_data': 'Borrar todos los datos',
      'clear_data_desc': 'Elimina pacientes y sesiones guardados',
      'confirm_delete': '¿Estás seguro?',
      'cancel': 'Cancelar',
      'delete': 'Eliminar',
      'about': 'Acerca de',
      'new_patient': 'Nuevo Paciente',
      'edit_patient': 'Editar Paciente',
      'save': 'Guardar',
      'name': 'Nombre',
      'age': 'Edad',
      'id': 'Identificación',
      'select_patient': 'Seleccionar Paciente',
      'no_patients': 'No hay pacientes registrados',
      'thermal_evolution': 'Evolución Térmica',
      'temperature_chart': 'Gráfica de Temperaturas',
      'search_patient': 'Buscar paciente...',
      'history': 'Historial',
      'delete_patient': 'Eliminar paciente',
      'delete_patient_desc': '¿Deseas eliminar a este paciente y todos sus registros?',
      'take_photo': 'Tomar Foto',
      'select_image': 'Seleccionar Imagen',
      'run_analysis': 'Ejecutar Análisis',
      'min_temp': 'Temp Mínima',
      'max_temp': 'Temp Máxima',
      'processing': 'Procesando...',
      'patient_details': 'Detalles del Paciente',
      'folders': 'Carpetas',
      'sessions': 'Sesiones',
      'download_manual': 'Descargar Manual de Usuario',
      'download_technical': 'Descargar Manual Técnico',
      'user_manual_desc': 'Instrucciones paso a paso para usar la aplicación.',
      'tech_manual_desc': 'Detalles técnicos y de arquitectura del sistema.',
      'downloading': 'Descargando...',
      'download_success': 'Manual descargado correctamente',
    },
    'en': {
      'app_title': 'Mamitas AI',
      'patients': 'Patients',
      'analysis': 'Analysis',
      'results': 'Results',
      'database': 'Database',
      'settings': 'Settings',
      'help': 'Help',
      'home': 'Home',
      'language': 'Language',
      'data': 'Data',
      'clear_data': 'Clear all data',
      'clear_data_desc': 'Deletes saved patients and sessions',
      'confirm_delete': 'Are you sure?',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'about': 'About',
      'new_patient': 'New Patient',
      'edit_patient': 'Edit Patient',
      'save': 'Save',
      'name': 'Name',
      'age': 'Age',
      'id': 'ID',
      'select_patient': 'Select Patient',
      'no_patients': 'No patients registered',
      'thermal_evolution': 'Thermal Evolution',
      'temperature_chart': 'Temperature Chart',
      'search_patient': 'Search patient...',
      'history': 'History',
      'delete_patient': 'Delete patient',
      'delete_patient_desc': 'Do you want to delete this patient and all their records?',
      'take_photo': 'Take Photo',
      'select_image': 'Select Image',
      'run_analysis': 'Run Analysis',
      'min_temp': 'Min Temp',
      'max_temp': 'Max Temp',
      'processing': 'Processing...',
      'patient_details': 'Patient Details',
      'folders': 'Folders',
      'sessions': 'Sessions',
      'download_manual': 'Download User Manual',
      'download_technical': 'Download Technical Manual',
      'user_manual_desc': 'Step-by-step instructions to use the app.',
      'tech_manual_desc': 'Technical and architecture details of the system.',
      'downloading': 'Downloading...',
      'download_success': 'Manual downloaded successfully',
    },
  };

  static String translate(String langCode, String key) {
    return _localizedValues[langCode]?[key] ?? _localizedValues['es']?[key] ?? key;
  }
}
